Setup a user = obsd
Allow root ssh login = prohibit-password
Password for root account = obsd
Password for user obsd = obsd
Public ssh key for user = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA+7dMcM3nnRYnQJrOb1WLaNjZcG5b3UQNuHTDEo1dUN obsd@obsd.sh
Public ssh key for root = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA+7dMcM3nnRYnQJrOb1WLaNjZcG5b3UQNuHTDEo1dUN obsd@obsd.sh
What timezone are you in = Europe/Berlin
URL to autopartitioning template for disklabel = http://10.0.2.1/disklabel
Which speed should com0 use = 115200
Do you expect to run the X Window System = no
